# Generated by Django 4.2.1 on 2023-06-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puppy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=75)),
                ('description', models.TextField(max_length=300)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
